-- AlterTable
ALTER TABLE "posts" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "edited_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "profiles" ALTER COLUMN "last_seen_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(3);
